### ISSUE TITLE
Error in OC 2.2.0.0

### ISSUE THREAD

**Issue by wayson-zipmoney** [beyondit/opencart-test-suite#2]
Hi,

I've a problem running the unit test cases. 

<img width="1416" alt="screen shot 2017-06-06 at 10 42 02 am" src="https://cloud.githubusercontent.com/assets/24888048/26809043/da05297e-4aa4-11e7-9cb3-a2841ad8f27d.png">

I've followed the readme introduction and copy the required files to the specific folder. But it's still not working.

Any ideas?

Thank you.

**Comment by stefanhuber** [comment]
Can you check if these two file are available?
 - "system/config/test-config.php"
 - "catalog/controller/startup/test_startup.php"

acctually if you install opencart-test-suite via composer these should be copied automatically. Might be the case that this hasn't happend.

**Comment by wayson-zipmoney** [comment]
Hi @stefanhuber ,

Thanks for reaching out. I did have these two files in those locations.

The weird thing is it works perfectly if I have a clean opencart install via CLI and installed your plugin. But it has the errors I posted if I installed this unit test library in a web installed version. Are they different?

I'm developing a open cart payment plugin and I need unit testing for it. The CLI version doesn't have functionality to install and initialised extensions.

**Comment by stefanhuber** [comment]
I am not 100% sure what you mean by a web installed version. I assume it was installed via the web installer? To be honest I have never used the web installer myself yet.

I use opencart with a project template I created for my purposes: https://github.com/beyondit/opencart-project-template

If the project is setup like this, everything should work. Depending on what you want to test, you might use phpunit only and mock your dependencies. Also for selenium tests you wouldn't need this framework...
