### ISSUE TITLE
Exception: Missing config file at: \config.php

### ISSUE THREAD

**Issue by TiredFingers** [beyondit/opencart-test-suite#9]
Hello! So I have this message when try to start CLI test with following params:  .\vendor\bin\phpunit --testsuite catalog-tests. 
OpenCart 3.0.2.0, php 7.2, phpunit from your bundle. opencart-test-suite installed using composer

It's my phpunit.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="vendor/autoload.php">
    <testsuites>
        <testsuite name="catalog-tests">
            <directory suffix="ModelCatalogManufacturerTest.php">./tests/catalog/</directory>
        </testsuite>
        <testsuite name="admin-tests">
            <directory suffix="AdminTest.php">./tests/admin/</directory>
        </testsuite>
    </testsuites>
    <php>
        <env name="OC_ROOT" value="../" />
        <env name="HTTP_SERVER" value="http://localhost:8080/" />
        <env name="TEST_CONFIG" value="test-config" />
    </php>
</phpunit>
```

**Comment by stefanhuber** [comment]
What message?

**Comment by TiredFingers** [comment]
> What message?

Exception: Missing config file at: \config.php

**Comment by stefanhuber** [comment]
ok sry.

This seems you have no opencart installation with a config file in place?
https://github.com/beyondit/opencart-test-suite/blob/master/src/OpenCartTest.php#L58

**Comment by TiredFingers** [comment]
> ok sry.
> 
> This seems you have no opencart installation with a config file in place?
> https://github.com/beyondit/opencart-test-suite/blob/master/src/OpenCartTest.php#L58

Thanks for reply. It's not just like that. The run script should be in another place. So few days with distrib and some of readme files helped me )
